# Goal
int32 CMD_CHOSE_BASE_PICK=0
int32 CMD_DRAW_OBJ=1
int32 CMD_CHOSE_OBJ=2
int32 CMD_CHOSE_BASE_PLACE=3
int32 CMD_CHOSE_LWA_PLACE=4
int32 cmd
---
# Result
int32 RES_SUCCESS=0
int32 RES_ERROR1=1
int32 RES_ERROR2=2
int32 RES_ERROR3=3
int32 RES_ERROR4=4
int32 RES_ERROR5=5
int32 RES_ERROR6=6
int32 res
string name
geometry_msgs/Pose pose
---
# Feedback

